import 'package:flutter/material.dart';

class CareProtocol {
  const CareProtocol({
    required this.id,
    required this.title,
    required this.category,
    required this.priority,
    required this.summary,
    required this.primaryAction,
    required this.secondaryAction,
    required this.icon,
    required this.color,
  });

  final String id;
  final String title;
  final String category;
  final String priority;
  final String summary;
  final String primaryAction;
  final String secondaryAction;
  final IconData icon;
  final Color color;
}

class LiveOperationsEvent {
  const LiveOperationsEvent({
    required this.id,
    required this.title,
    required this.area,
    required this.status,
    required this.eta,
    required this.actor,
    required this.icon,
    required this.color,
  });

  final String id;
  final String title;
  final String area;
  final String status;
  final String eta;
  final String actor;
  final IconData icon;
  final Color color;
}

class DoctorSpecialityGuide {
  const DoctorSpecialityGuide({
    required this.name,
    required this.whenToUse,
    required this.commonSymptoms,
    required this.preferredSlot,
    required this.averageFee,
    required this.icon,
    required this.color,
  });

  final String name;
  final String whenToUse;
  final String commonSymptoms;
  final String preferredSlot;
  final String averageFee;
  final IconData icon;
  final Color color;
}

class SchemeEducationCard {
  const SchemeEducationCard({
    required this.title,
    required this.department,
    required this.benefit,
    required this.eligibility,
    required this.document,
    required this.action,
    required this.icon,
    required this.color,
  });

  final String title;
  final String department;
  final String benefit;
  final String eligibility;
  final String document;
  final String action;
  final IconData icon;
  final Color color;
}

const professionalCareProtocols = [
  CareProtocol(
    id: 'CP-001',
    title: 'Chest pain response',
    category: 'Cardiac',
    priority: 'Critical',
    summary:
        'Use this protocol when the user reports chest pain, sweating, shortness of breath, or radiating arm pain.',
    primaryAction: 'Trigger SOS and recommend nearest cardiac emergency unit.',
    secondaryAction:
        'Keep patient seated, avoid exertion, and prepare medical history.',
    icon: Icons.monitor_heart_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-002',
    title: 'Breathing difficulty',
    category: 'Respiratory',
    priority: 'Critical',
    summary:
        'Use this protocol for severe breathlessness, wheezing, asthma flare, or low oxygen indication.',
    primaryAction: 'Show nearby emergency hospitals with oxygen support.',
    secondaryAction:
        'Ask the user to sit upright and keep inhaler details ready.',
    icon: Icons.air_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-003',
    title: 'Road accident triage',
    category: 'Trauma',
    priority: 'Critical',
    summary:
        'Use this protocol when the user reports road injury, bleeding, fracture, or unconsciousness.',
    primaryAction:
        'Trigger SOS, share live location, and suggest trauma center.',
    secondaryAction:
        'Do not move injured person unless the location is unsafe.',
    icon: Icons.emergency_share_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-004',
    title: 'High fever guidance',
    category: 'General Medicine',
    priority: 'High',
    summary:
        'Use this protocol for fever above 102 F, chills, weakness, dehydration, or persistent infection symptoms.',
    primaryAction: 'Recommend physician consultation and hydration reminders.',
    secondaryAction: 'Show lab and hospital options if fever persists.',
    icon: Icons.thermostat_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-005',
    title: 'Child fever fast path',
    category: 'Pediatrics',
    priority: 'High',
    summary:
        'Use this protocol for infants and children with high fever, vomiting, lethargy, or rash.',
    primaryAction:
        'Prioritize pediatrician slots and nearest pediatric emergency.',
    secondaryAction:
        'Ask guardian to note age, weight, temperature, and medicine given.',
    icon: Icons.child_care_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-006',
    title: 'Pregnancy emergency',
    category: 'Gynecology',
    priority: 'Critical',
    summary:
        'Use this protocol for pregnancy bleeding, severe pain, reduced fetal movement, or dizziness.',
    primaryAction: 'Show obstetric emergency units and start SOS contact flow.',
    secondaryAction: 'Keep maternity records and doctor contact visible.',
    icon: Icons.pregnant_woman_rounded,
    color: Color(0xFFD946EF),
  ),
  CareProtocol(
    id: 'CP-007',
    title: 'Stroke warning',
    category: 'Neurology',
    priority: 'Critical',
    summary:
        'Use this protocol for face drooping, arm weakness, speech trouble, sudden confusion, or imbalance.',
    primaryAction:
        'Trigger emergency hospital navigation with stroke-ready filter.',
    secondaryAction:
        'Record last-known-normal time and avoid giving food or water.',
    icon: Icons.psychology_alt_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-008',
    title: 'Severe allergic reaction',
    category: 'Allergy',
    priority: 'Critical',
    summary:
        'Use this protocol for swelling, hives, breathing trouble, or known anaphylaxis risk.',
    primaryAction: 'Start SOS and route to nearest emergency department.',
    secondaryAction: 'Ask whether an epinephrine auto injector is available.',
    icon: Icons.sick_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-009',
    title: 'Diabetes low sugar',
    category: 'Endocrine',
    priority: 'High',
    summary:
        'Use this protocol for sweating, shakiness, confusion, faintness, or known hypoglycemia.',
    primaryAction: 'Prompt sugar intake if conscious and show nearby care.',
    secondaryAction: 'Notify emergency contact if symptoms worsen.',
    icon: Icons.bloodtype_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-010',
    title: 'Seizure safety',
    category: 'Neurology',
    priority: 'Critical',
    summary:
        'Use this protocol when seizure activity, collapse, or repeated fits are reported.',
    primaryAction: 'Start timer, alert contacts, and suggest emergency unit.',
    secondaryAction: 'Move objects away and do not restrain the patient.',
    icon: Icons.timer_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-011',
    title: 'Burn injury support',
    category: 'Trauma',
    priority: 'High',
    summary:
        'Use this protocol for thermal, chemical, or electrical burns with pain, blistering, or large area involvement.',
    primaryAction: 'Show burn-capable hospitals and first-aid guidance.',
    secondaryAction:
        'Cool with running water and avoid applying creams initially.',
    icon: Icons.local_fire_department_rounded,
    color: Color(0xFFFF5722),
  ),
  CareProtocol(
    id: 'CP-012',
    title: 'Snake bite response',
    category: 'Emergency',
    priority: 'Critical',
    summary:
        'Use this protocol for suspected snake bite, swelling, pain, or bite marks.',
    primaryAction: 'Route to hospital with anti-venom capability.',
    secondaryAction: 'Keep limb still and avoid cutting or sucking the wound.',
    icon: Icons.warning_amber_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-013',
    title: 'Poison ingestion',
    category: 'Emergency',
    priority: 'Critical',
    summary:
        'Use this protocol for suspected poisoning, chemical ingestion, or overdose.',
    primaryAction: 'Start SOS and connect to emergency care.',
    secondaryAction: 'Keep container or medicine strip ready for clinicians.',
    icon: Icons.science_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-014',
    title: 'Dehydration support',
    category: 'General Medicine',
    priority: 'Medium',
    summary:
        'Use this protocol for dizziness, dry mouth, low urine, heat exposure, or repeated vomiting.',
    primaryAction:
        'Recommend ORS, hydration tracking, and doctor slot if severe.',
    secondaryAction: 'Suggest urgent care if confusion or fainting occurs.',
    icon: Icons.water_drop_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-015',
    title: 'Dengue suspicion',
    category: 'Infectious Disease',
    priority: 'High',
    summary:
        'Use this protocol for fever, body ache, rash, low platelets, or dengue season risk.',
    primaryAction: 'Show physician slots and lab test suggestions.',
    secondaryAction: 'Avoid self-medication with high-risk painkillers.',
    icon: Icons.bug_report_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-016',
    title: 'COVID respiratory check',
    category: 'Infectious Disease',
    priority: 'High',
    summary:
        'Use this protocol for cough, fever, low oxygen, exposure risk, or breathing discomfort.',
    primaryAction: 'Show teleconsult and oxygen-ready hospitals.',
    secondaryAction: 'Recommend mask use and isolation until doctor advice.',
    icon: Icons.coronavirus_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-017',
    title: 'Mental health crisis',
    category: 'Mental Health',
    priority: 'Critical',
    summary:
        'Use this protocol for panic attack, self-harm risk, severe distress, or unsafe thoughts.',
    primaryAction: 'Offer emergency contact alert and crisis support options.',
    secondaryAction: 'Keep the user connected and avoid leaving them alone.',
    icon: Icons.volunteer_activism_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-018',
    title: 'Panic attack calm path',
    category: 'Mental Health',
    priority: 'Medium',
    summary:
        'Use this protocol for palpitations, fear, trembling, fast breathing, or panic symptoms.',
    primaryAction:
        'Start breathing timer and offer therapist or physician slot.',
    secondaryAction: 'Guide grounding and hydration while monitoring symptoms.',
    icon: Icons.self_improvement_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-019',
    title: 'Elder fall alert',
    category: 'Geriatric',
    priority: 'High',
    summary:
        'Use this protocol for senior citizen fall, hip pain, head injury, or inability to stand.',
    primaryAction:
        'Notify emergency contacts and route to orthopedic emergency.',
    secondaryAction:
        'Avoid moving the person until assessment if pain is severe.',
    icon: Icons.elderly_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-020',
    title: 'Medication refill',
    category: 'Pharmacy',
    priority: 'Low',
    summary:
        'Use this protocol when the user needs regular medicine refill or affordable substitute search.',
    primaryAction: 'Show Jan Aushadhi Kendras and prescription records.',
    secondaryAction: 'Remind user to confirm substitution with clinician.',
    icon: Icons.medication_liquid_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-021',
    title: 'Eye injury support',
    category: 'Ophthalmology',
    priority: 'High',
    summary:
        'Use this protocol for eye trauma, chemical splash, sudden pain, or sudden vision loss.',
    primaryAction: 'Route to eye emergency and start contact alert if severe.',
    secondaryAction:
        'Avoid rubbing eye and rinse chemical exposure with clean water.',
    icon: Icons.visibility_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-022',
    title: 'Dental emergency',
    category: 'Dental',
    priority: 'Medium',
    summary:
        'Use this protocol for severe tooth pain, swelling, injury, or bleeding gums.',
    primaryAction:
        'Show emergency dentist availability and pain-care guidance.',
    secondaryAction: 'Keep medication allergy and recent dental history ready.',
    icon: Icons.medical_services_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-023',
    title: 'Hypertension warning',
    category: 'Cardiac',
    priority: 'High',
    summary:
        'Use this protocol for very high blood pressure, headache, chest pain, or blurred vision.',
    primaryAction:
        'Recommend urgent doctor review and emergency care if symptoms exist.',
    secondaryAction: 'Ask user to recheck reading calmly after five minutes.',
    icon: Icons.speed_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-024',
    title: 'Kidney stone pain',
    category: 'Urology',
    priority: 'Medium',
    summary:
        'Use this protocol for flank pain, urinary symptoms, nausea, or known stone history.',
    primaryAction: 'Show urologist slots and nearby imaging centers.',
    secondaryAction: 'Prompt hydration unless restricted by doctor advice.',
    icon: Icons.water_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-025',
    title: 'Severe abdominal pain',
    category: 'Gastroenterology',
    priority: 'High',
    summary:
        'Use this protocol for sharp abdominal pain, vomiting, fever, or worsening discomfort.',
    primaryAction: 'Recommend urgent physician or emergency hospital.',
    secondaryAction:
        'Avoid heavy food and record pain location and onset time.',
    icon: Icons.healing_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-026',
    title: 'Skin infection',
    category: 'Dermatology',
    priority: 'Medium',
    summary:
        'Use this protocol for redness, swelling, pus, rash, or spreading infection.',
    primaryAction: 'Show dermatologist availability and image upload prompt.',
    secondaryAction: 'Avoid scratching and keep affected area clean.',
    icon: Icons.front_hand_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-027',
    title: 'Ear pain child',
    category: 'ENT',
    priority: 'Medium',
    summary:
        'Use this protocol for child ear pain, fever, discharge, or hearing discomfort.',
    primaryAction: 'Prioritize pediatric ENT or pediatrician slots.',
    secondaryAction: 'Avoid inserting objects or drops without medical advice.',
    icon: Icons.hearing_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-028',
    title: 'Asthma follow-up',
    category: 'Respiratory',
    priority: 'Medium',
    summary:
        'Use this protocol for regular asthma review, inhaler refill, or mild wheeze.',
    primaryAction: 'Show pulmonologist slots and medicine reminders.',
    secondaryAction: 'Ask user to track triggers and peak flow if available.',
    icon: Icons.air_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-029',
    title: 'Vaccination reminder',
    category: 'Preventive Care',
    priority: 'Low',
    summary: 'Use this protocol for child or adult vaccine scheduling.',
    primaryAction: 'Show available vaccine centers and pediatrician slots.',
    secondaryAction: 'Add reminder to appointment timeline.',
    icon: Icons.vaccines_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-030',
    title: 'Lab report review',
    category: 'Diagnostics',
    priority: 'Low',
    summary:
        'Use this protocol when the user wants a doctor to review uploaded reports.',
    primaryAction:
        'Suggest general physician or specialist based on report type.',
    secondaryAction: 'Show secure health-record upload card.',
    icon: Icons.fact_check_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-031',
    title: 'Post surgery concern',
    category: 'Surgery',
    priority: 'High',
    summary:
        'Use this protocol for fever, wound discharge, swelling, pain, or bleeding after surgery.',
    primaryAction: 'Route to surgeon follow-up or nearest emergency if severe.',
    secondaryAction: 'Ask user to keep discharge summary ready.',
    icon: Icons.local_hospital_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-032',
    title: 'Back pain support',
    category: 'Orthopedic',
    priority: 'Medium',
    summary:
        'Use this protocol for back pain, sciatica, injury, or movement limitation.',
    primaryAction: 'Show orthopedic and physiotherapy options.',
    secondaryAction:
        'Flag emergency if weakness, numbness, or bladder symptoms appear.',
    icon: Icons.accessibility_new_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-033',
    title: 'Migraine episode',
    category: 'Neurology',
    priority: 'Medium',
    summary:
        'Use this protocol for repeated headache, light sensitivity, nausea, or migraine history.',
    primaryAction: 'Show neurologist slot and symptom tracker.',
    secondaryAction: 'Suggest quiet dark room while waiting for advice.',
    icon: Icons.psychology_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-034',
    title: 'Anemia fatigue',
    category: 'General Medicine',
    priority: 'Low',
    summary:
        'Use this protocol for fatigue, dizziness, paleness, or known anemia.',
    primaryAction: 'Suggest physician consultation and lab check.',
    secondaryAction: 'Show diet and medicine reminder modules.',
    icon: Icons.bloodtype_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-035',
    title: 'Thyroid follow-up',
    category: 'Endocrine',
    priority: 'Low',
    summary:
        'Use this protocol for thyroid report review, medicine reminder, or weight symptoms.',
    primaryAction: 'Show endocrinologist slots and lab trend view.',
    secondaryAction: 'Recommend regular medicine timing reminder.',
    icon: Icons.timeline_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-036',
    title: 'Blood donation need',
    category: 'Community Health',
    priority: 'High',
    summary:
        'Use this protocol when a user requests urgent blood donor discovery.',
    primaryAction: 'Show blood banks and verified donor network.',
    secondaryAction: 'Confirm blood group and hospital location.',
    icon: Icons.bloodtype_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-037',
    title: 'Ambulance unavailable fallback',
    category: 'Transport',
    priority: 'Critical',
    summary:
        'Use this protocol when ambulance delay is reported and emergency cab may be needed.',
    primaryAction: 'Open emergency cab flow with hospital drop prefilled.',
    secondaryAction: 'Notify driver that ride is emergency tagged.',
    icon: Icons.local_taxi_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-038',
    title: 'Hospital bed inquiry',
    category: 'Hospital',
    priority: 'High',
    summary:
        'Use this protocol for finding hospital beds, ICU, oxygen, or emergency admission.',
    primaryAction: 'Show hospitals with live availability status.',
    secondaryAction: 'Call hospital desk and save response in timeline.',
    icon: Icons.bed_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-039',
    title: 'Insurance document check',
    category: 'Finance',
    priority: 'Low',
    summary:
        'Use this protocol for policy card, claim documents, or scheme eligibility.',
    primaryAction: 'Open document checklist and upload vault.',
    secondaryAction: 'Show Ayushman or employer insurance next steps.',
    icon: Icons.assignment_turned_in_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-040',
    title: 'Rural care navigation',
    category: 'Access',
    priority: 'Medium',
    summary:
        'Use this protocol when user is outside city coverage or network is limited.',
    primaryAction: 'Show offline-ready emergency contacts and nearest PHC.',
    secondaryAction: 'Cache map route and emergency instructions.',
    icon: Icons.map_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-041',
    title: 'Follow-up appointment',
    category: 'Care Continuity',
    priority: 'Low',
    summary:
        'Use this protocol for booking a repeat visit after consultation or report review.',
    primaryAction: 'Suggest same doctor next available slot.',
    secondaryAction: 'Attach previous prescription and reports.',
    icon: Icons.event_repeat_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-042',
    title: 'Prescription renewal',
    category: 'Pharmacy',
    priority: 'Low',
    summary:
        'Use this protocol for renewing long-term medication prescriptions.',
    primaryAction: 'Show doctor teleconsult and nearby medicine stores.',
    secondaryAction: 'Add refill reminders after prescription update.',
    icon: Icons.receipt_long_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-043',
    title: 'Home care nursing',
    category: 'Home Care',
    priority: 'Medium',
    summary:
        'Use this protocol for injection, dressing, elder care, or home vitals support.',
    primaryAction: 'Show verified home care partners and schedule cards.',
    secondaryAction: 'Confirm address, timing, and care instruction notes.',
    icon: Icons.home_work_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-044',
    title: 'Physiotherapy plan',
    category: 'Rehabilitation',
    priority: 'Low',
    summary:
        'Use this protocol for pain recovery, post-injury rehab, or mobility program.',
    primaryAction: 'Show physiotherapist slots and exercise plan tracker.',
    secondaryAction: 'Remind user to consult doctor for severe pain.',
    icon: Icons.fitness_center_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-045',
    title: 'Nutrition consult',
    category: 'Wellness',
    priority: 'Low',
    summary:
        'Use this protocol for diet planning, diabetes diet, weight goals, or anemia diet.',
    primaryAction: 'Show dietitian slots and food preference form.',
    secondaryAction: 'Attach lab reports if available.',
    icon: Icons.restaurant_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-046',
    title: 'Health record sync',
    category: 'Records',
    priority: 'Low',
    summary:
        'Use this protocol to organize reports, prescriptions, allergies, and vitals history.',
    primaryAction: 'Open secure record vault and smart tagging flow.',
    secondaryAction: 'Prompt user to add emergency allergies.',
    icon: Icons.folder_shared_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-047',
    title: 'Allergy profile update',
    category: 'Safety',
    priority: 'Medium',
    summary:
        'Use this protocol to keep medicine, food, and environmental allergy details ready for emergencies.',
    primaryAction: 'Open allergy editor and emergency card.',
    secondaryAction: 'Remind user to verify severe allergies with doctor.',
    icon: Icons.warning_rounded,
    color: Color(0xFFFF9800),
  ),
  CareProtocol(
    id: 'CP-048',
    title: 'Family profile switch',
    category: 'Family Care',
    priority: 'Low',
    summary:
        'Use this protocol when a user manages care for children, parents, or dependents.',
    primaryAction: 'Show family members and care timeline.',
    secondaryAction: 'Restrict sensitive data with consent controls.',
    icon: Icons.family_restroom_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-049',
    title: 'Second opinion',
    category: 'Consultation',
    priority: 'Low',
    summary:
        'Use this protocol when a user wants another doctor to review diagnosis or treatment.',
    primaryAction: 'Show specialists and document upload checklist.',
    secondaryAction: 'Summarize existing diagnosis and medication.',
    icon: Icons.manage_search_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-050',
    title: 'Emergency contact drill',
    category: 'Preparedness',
    priority: 'Low',
    summary:
        'Use this protocol to test emergency contact numbers and permissions before real emergencies.',
    primaryAction: 'Run silent verification and permission checklist.',
    secondaryAction: 'Show missing location or SMS permissions.',
    icon: Icons.verified_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-051',
    title: 'Low network SOS mode',
    category: 'Reliability',
    priority: 'Critical',
    summary:
        'Use this protocol when internet is weak and emergency communication must still work.',
    primaryAction: 'Fallback to SMS with last known location.',
    secondaryAction: 'Queue app notification retries when network returns.',
    icon: Icons.signal_cellular_connected_no_internet_4_bar_rounded,
    color: Color(0xFFF22635),
  ),
  CareProtocol(
    id: 'CP-052',
    title: 'Women safety escort',
    category: 'Safety',
    priority: 'High',
    summary:
        'Use this protocol when a user requests escorted travel to hospital or pharmacy at night.',
    primaryAction: 'Share live trip with emergency contacts.',
    secondaryAction: 'Keep cab driver identity and route visible.',
    icon: Icons.shield_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-053',
    title: 'Night pharmacy search',
    category: 'Pharmacy',
    priority: 'Medium',
    summary: 'Use this protocol to locate open pharmacies during late hours.',
    primaryAction: 'Show 24x7 pharmacy and Jan Aushadhi alternatives.',
    secondaryAction: 'Call store before navigation if stock is critical.',
    icon: Icons.nightlight_round,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-054',
    title: 'Hospital discharge plan',
    category: 'Care Continuity',
    priority: 'Medium',
    summary:
        'Use this protocol after hospital discharge for medicines, follow-up, and warning signs.',
    primaryAction: 'Create discharge checklist and reminder schedule.',
    secondaryAction: 'Attach emergency readmission instructions.',
    icon: Icons.checklist_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-055',
    title: 'Caregiver handoff',
    category: 'Family Care',
    priority: 'Medium',
    summary:
        'Use this protocol when responsibility shifts to another family member or caregiver.',
    primaryAction: 'Share care summary with approved contact.',
    secondaryAction: 'Include medicine timing and doctor contacts.',
    icon: Icons.handshake_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-056',
    title: 'Senior medicine reminder',
    category: 'Geriatric',
    priority: 'Low',
    summary:
        'Use this protocol for older adults with daily medication schedules.',
    primaryAction: 'Create smart reminders with missed dose alerts.',
    secondaryAction: 'Notify caregiver only after repeated misses.',
    icon: Icons.alarm_rounded,
    color: Color(0xFF079C66),
  ),
  CareProtocol(
    id: 'CP-057',
    title: 'Infant feeding concern',
    category: 'Pediatrics',
    priority: 'Medium',
    summary:
        'Use this protocol for poor feeding, vomiting, dehydration signs, or infant irritability.',
    primaryAction: 'Prioritize pediatric consultation and hydration warning.',
    secondaryAction: 'Record age, weight, wet diaper count, and fever.',
    icon: Icons.child_friendly_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-058',
    title: 'Telemedicine fallback',
    category: 'Access',
    priority: 'Medium',
    summary:
        'Use this protocol when clinic visit is not possible but symptoms need review.',
    primaryAction: 'Offer video or audio consultation slot.',
    secondaryAction: 'Escalate to hospital if red flags are selected.',
    icon: Icons.video_call_rounded,
    color: Color(0xFF2474D8),
  ),
  CareProtocol(
    id: 'CP-059',
    title: 'Medical certificate request',
    category: 'Documentation',
    priority: 'Low',
    summary:
        'Use this protocol when a user needs visit proof, fitness certificate, or work note.',
    primaryAction: 'Show doctor appointment and document request checklist.',
    secondaryAction: 'Keep certificate generation behind doctor approval.',
    icon: Icons.badge_rounded,
    color: Color(0xFF7C3AED),
  ),
  CareProtocol(
    id: 'CP-060',
    title: 'Preventive annual checkup',
    category: 'Preventive Care',
    priority: 'Low',
    summary:
        'Use this protocol for routine health checkup planning and package comparison.',
    primaryAction: 'Show nearby diagnostic packages and physician review.',
    secondaryAction: 'Add annual reminder after completion.',
    icon: Icons.health_and_safety_rounded,
    color: Color(0xFF079C66),
  ),
];

const liveOperationsEvents = [
  LiveOperationsEvent(
    id: 'EV-001',
    title: 'SOS route prepared',
    area: 'Vijay Nagar',
    status: 'Ready',
    eta: '3 min',
    actor: 'Apollo emergency desk',
    icon: Icons.route_rounded,
    color: Color(0xFFF22635),
  ),
  LiveOperationsEvent(
    id: 'EV-002',
    title: 'Emergency cab assigned',
    area: 'Malviya Nagar',
    status: 'Driver notified',
    eta: '5 min',
    actor: 'Cab partner network',
    icon: Icons.local_taxi_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-003',
    title: 'Cardiologist slot opened',
    area: 'AB Road',
    status: 'Bookable',
    eta: '11:30 AM',
    actor: 'Dr. Ananya Sharma',
    icon: Icons.monitor_heart_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-004',
    title: 'Jan Aushadhi store online',
    area: 'Palasia',
    status: 'Open',
    eta: '4.1 km',
    actor: 'Affordable pharmacy',
    icon: Icons.medication_liquid_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-005',
    title: 'Ayushman eligibility queue',
    area: 'Indore',
    status: 'Checking',
    eta: '2 min',
    actor: 'Scheme desk',
    icon: Icons.savings_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-006',
    title: 'Hospital bed status refreshed',
    area: 'Rau',
    status: 'Updated',
    eta: 'Now',
    actor: 'Network monitor',
    icon: Icons.bed_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-007',
    title: 'Emergency contacts verified',
    area: 'Profile',
    status: '3 active',
    eta: 'Now',
    actor: 'Safety check',
    icon: Icons.groups_2_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-008',
    title: 'Doctor report review started',
    area: 'Health records',
    status: 'In progress',
    eta: '8 min',
    actor: 'Clinical assistant',
    icon: Icons.fact_check_rounded,
    color: Color(0xFF7C3AED),
  ),
  LiveOperationsEvent(
    id: 'EV-009',
    title: 'Nearest trauma center pinned',
    area: 'Bhawarkuan',
    status: 'Pinned',
    eta: '6 min',
    actor: 'Map engine',
    icon: Icons.local_hospital_rounded,
    color: Color(0xFFF22635),
  ),
  LiveOperationsEvent(
    id: 'EV-010',
    title: 'Pediatrician slot changed',
    area: 'Old Palasia',
    status: 'Available',
    eta: 'Tomorrow',
    actor: 'Dr. Neha Patel',
    icon: Icons.child_care_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-011',
    title: 'Medicine stock confirmed',
    area: 'Vijay Nagar',
    status: 'Confirmed',
    eta: '2.7 km',
    actor: 'Jan Aushadhi desk',
    icon: Icons.inventory_2_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-012',
    title: 'Ambulance fallback checked',
    area: 'MR 10',
    status: 'Cab suggested',
    eta: '7 min',
    actor: 'Transport monitor',
    icon: Icons.emergency_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-013',
    title: 'Night pharmacy route',
    area: 'Saket',
    status: 'Open',
    eta: '12 min',
    actor: 'Pharmacy network',
    icon: Icons.nightlight_round,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-014',
    title: 'Allergy warning synced',
    area: 'Emergency card',
    status: 'Visible',
    eta: 'Now',
    actor: 'Profile vault',
    icon: Icons.warning_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-015',
    title: 'Follow-up reminder created',
    area: 'Appointments',
    status: 'Scheduled',
    eta: 'May 18',
    actor: 'Care timeline',
    icon: Icons.event_repeat_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-016',
    title: 'Vitals trend updated',
    area: 'Health records',
    status: 'Synced',
    eta: 'Now',
    actor: 'Wearable bridge',
    icon: Icons.timeline_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-017',
    title: 'Emergency SMS queued',
    area: 'Low network',
    status: 'Queued',
    eta: 'Retrying',
    actor: 'Reliability layer',
    icon: Icons.sms_rounded,
    color: Color(0xFFF22635),
  ),
  LiveOperationsEvent(
    id: 'EV-018',
    title: 'Caregiver notified',
    area: 'Family profile',
    status: 'Delivered',
    eta: 'Now',
    actor: 'Priya Sharma',
    icon: Icons.family_restroom_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-019',
    title: 'Lab package compared',
    area: 'Diagnostics',
    status: 'Best price',
    eta: 'Rs. 599',
    actor: 'Diagnostics hub',
    icon: Icons.biotech_rounded,
    color: Color(0xFF7C3AED),
  ),
  LiveOperationsEvent(
    id: 'EV-020',
    title: 'Insurance document ready',
    area: 'Claims',
    status: 'Complete',
    eta: 'Now',
    actor: 'Document vault',
    icon: Icons.assignment_turned_in_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-021',
    title: 'Oxygen support filter',
    area: 'Hospital search',
    status: 'Applied',
    eta: '18 results',
    actor: 'Hospital network',
    icon: Icons.air_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-022',
    title: 'Emergency cab driver read note',
    area: 'Route',
    status: 'Seen',
    eta: '4 min',
    actor: 'Driver Mahesh',
    icon: Icons.visibility_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-023',
    title: 'Teleconsult room opened',
    area: 'Video care',
    status: 'Waiting',
    eta: '2 min',
    actor: 'Dr. Rohit Verma',
    icon: Icons.video_call_rounded,
    color: Color(0xFF2474D8),
  ),
  LiveOperationsEvent(
    id: 'EV-024',
    title: 'Blood bank result found',
    area: 'Indore',
    status: 'Available',
    eta: '3 units',
    actor: 'Blood bank registry',
    icon: Icons.bloodtype_rounded,
    color: Color(0xFFF22635),
  ),
  LiveOperationsEvent(
    id: 'EV-025',
    title: 'Prescription reminder due',
    area: 'Medication',
    status: 'Due',
    eta: '8:00 PM',
    actor: 'Care reminder',
    icon: Icons.alarm_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-026',
    title: 'Scheme hospital matched',
    area: 'Ayushman',
    status: 'Eligible',
    eta: 'Apollo',
    actor: 'Scheme engine',
    icon: Icons.verified_user_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-027',
    title: 'SOS drill completed',
    area: 'Preparedness',
    status: 'Passed',
    eta: 'Now',
    actor: 'Safety check',
    icon: Icons.verified_rounded,
    color: Color(0xFF079C66),
  ),
  LiveOperationsEvent(
    id: 'EV-028',
    title: 'Follow-up report missing',
    area: 'Records',
    status: 'Action needed',
    eta: 'Upload',
    actor: 'Care timeline',
    icon: Icons.upload_file_rounded,
    color: Color(0xFFFF9800),
  ),
  LiveOperationsEvent(
    id: 'EV-029',
    title: 'Emergency contact offline',
    area: 'Safety',
    status: 'Backup ready',
    eta: 'Now',
    actor: 'Contact monitor',
    icon: Icons.contact_phone_rounded,
    color: Color(0xFFF22635),
  ),
  LiveOperationsEvent(
    id: 'EV-030',
    title: 'Nearest clinic expanded',
    area: 'Search',
    status: 'Updated',
    eta: '12 clinics',
    actor: 'Maps layer',
    icon: Icons.place_rounded,
    color: Color(0xFF2474D8),
  ),
];

const specialityGuides = [
  DoctorSpecialityGuide(
    name: 'Cardiologist',
    whenToUse: 'Chest pain, palpitations, blood pressure, breathlessness.',
    commonSymptoms: 'Chest discomfort, sweating, dizziness, arm pain.',
    preferredSlot: 'Morning',
    averageFee: 'Rs. 800',
    icon: Icons.monitor_heart_rounded,
    color: Color(0xFFF22635),
  ),
  DoctorSpecialityGuide(
    name: 'Orthopedic',
    whenToUse: 'Bone, joint, fracture, spine, or sports injury care.',
    commonSymptoms: 'Pain, swelling, restricted movement, injury.',
    preferredSlot: 'Afternoon',
    averageFee: 'Rs. 600',
    icon: Icons.accessibility_new_rounded,
    color: Color(0xFFFF9800),
  ),
  DoctorSpecialityGuide(
    name: 'Pediatrician',
    whenToUse: 'Child fever, vaccination, nutrition, and growth review.',
    commonSymptoms: 'Fever, cough, vomiting, feeding concern.',
    preferredSlot: 'Morning',
    averageFee: 'Rs. 500',
    icon: Icons.child_care_rounded,
    color: Color(0xFF2474D8),
  ),
  DoctorSpecialityGuide(
    name: 'Dermatologist',
    whenToUse: 'Skin, hair, nail, allergy, rash, and infection care.',
    commonSymptoms: 'Itching, redness, acne, patches, swelling.',
    preferredSlot: 'Evening',
    averageFee: 'Rs. 700',
    icon: Icons.front_hand_rounded,
    color: Color(0xFF079C66),
  ),
  DoctorSpecialityGuide(
    name: 'Gynecologist',
    whenToUse: 'Pregnancy, menstrual health, fertility, and women care.',
    commonSymptoms: 'Pain, bleeding, irregular cycle, pregnancy symptoms.',
    preferredSlot: 'Morning',
    averageFee: 'Rs. 750',
    icon: Icons.pregnant_woman_rounded,
    color: Color(0xFFD946EF),
  ),
  DoctorSpecialityGuide(
    name: 'Neurologist',
    whenToUse: 'Headache, seizure, stroke warning, nerve or brain symptoms.',
    commonSymptoms: 'Weakness, confusion, fits, severe headache.',
    preferredSlot: 'Afternoon',
    averageFee: 'Rs. 900',
    icon: Icons.psychology_alt_rounded,
    color: Color(0xFF7C3AED),
  ),
  DoctorSpecialityGuide(
    name: 'ENT Specialist',
    whenToUse: 'Ear, nose, throat, hearing, sinus, or voice concerns.',
    commonSymptoms: 'Ear pain, blocked nose, throat pain, discharge.',
    preferredSlot: 'Evening',
    averageFee: 'Rs. 550',
    icon: Icons.hearing_rounded,
    color: Color(0xFF2474D8),
  ),
  DoctorSpecialityGuide(
    name: 'Pulmonologist',
    whenToUse: 'Asthma, breathing trouble, cough, oxygen, and lung care.',
    commonSymptoms: 'Wheezing, cough, breathlessness, low SpO2.',
    preferredSlot: 'Morning',
    averageFee: 'Rs. 850',
    icon: Icons.air_rounded,
    color: Color(0xFF2474D8),
  ),
  DoctorSpecialityGuide(
    name: 'Dentist',
    whenToUse: 'Tooth pain, dental injury, gum swelling, cleaning.',
    commonSymptoms: 'Pain, swelling, bleeding, sensitivity.',
    preferredSlot: 'Evening',
    averageFee: 'Rs. 450',
    icon: Icons.medical_services_rounded,
    color: Color(0xFF079C66),
  ),
  DoctorSpecialityGuide(
    name: 'General Physician',
    whenToUse: 'Fever, weakness, infection, reports, and first consultation.',
    commonSymptoms: 'Fever, cough, fatigue, body ache.',
    preferredSlot: 'Anytime',
    averageFee: 'Rs. 400',
    icon: Icons.health_and_safety_rounded,
    color: Color(0xFF079C66),
  ),
];

const schemeEducationCards = [
  SchemeEducationCard(
    title: 'Ayushman Bharat PM-JAY',
    department: 'National Health Authority',
    benefit: 'Cashless care up to Rs. 5,00,000 per eligible family per year.',
    eligibility: 'Based on approved beneficiary database and family criteria.',
    document: 'Aadhaar, ration card, or approved identity document.',
    action: 'Check eligibility and find empanelled hospitals.',
    icon: Icons.savings_rounded,
    color: Color(0xFF079C66),
  ),
  SchemeEducationCard(
    title: 'Jan Aushadhi Yojana',
    department: 'Department of Pharmaceuticals',
    benefit: 'Affordable quality generic medicines through dedicated kendras.',
    eligibility: 'Available to all citizens through participating stores.',
    document: 'Prescription may be needed for scheduled medicines.',
    action: 'Find nearest kendra and call for stock confirmation.',
    icon: Icons.medication_liquid_rounded,
    color: Color(0xFF079C66),
  ),
  SchemeEducationCard(
    title: 'CGHS',
    department: 'Central Government Health Scheme',
    benefit:
        'Healthcare support for eligible central government employees and pensioners.',
    eligibility: 'Applicable for registered CGHS beneficiaries.',
    document: 'CGHS card and approved beneficiary details.',
    action: 'Find empanelled clinics and wellness centers.',
    icon: Icons.verified_user_rounded,
    color: Color(0xFF2474D8),
  ),
  SchemeEducationCard(
    title: 'ESIC',
    department: 'Employees State Insurance',
    benefit: 'Medical care and insurance benefits for eligible workers.',
    eligibility: 'Employees covered under ESIC contribution rules.',
    document: 'ESIC card or insurance number.',
    action: 'Locate ESIC hospitals and dispensaries.',
    icon: Icons.badge_rounded,
    color: Color(0xFFFF9800),
  ),
  SchemeEducationCard(
    title: 'State Health Assistance',
    department: 'State Health Department',
    benefit: 'State-specific financial support and hospital access.',
    eligibility: 'Depends on income, residence, and category rules.',
    document: 'Address proof, income certificate, and identity proof.',
    action: 'View state scheme help desk and hospitals.',
    icon: Icons.account_balance_rounded,
    color: Color(0xFF7C3AED),
  ),
];
